# SITE CONFIGURATION
title: PANDAS Lab # your site title
author: Benjamin J. Radford # You :P
description: > # Meta description of Homepage
  PANDAS Lab: Politics, AI, and Data Science. This research lab is run by 
  professors Benjamin J. Radford and Yaoyao Dai.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pandas-lab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:title

# SEO PLUGIN
social:
  name: Benjamin J. Radford
  links:
    - https://twitter.com/ben_j_radford
    - https://github.com/pandas-lab

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Join', link: '/join'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'Contact', link: '/contact'}


tagline: >
  Politics, AI, and Data Science research lab. 

hero_img: /bamboo-08.jpeg 
#logo_img: /pandas-logo-sq.png

email: your-email@domain.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache

include: ['_pages',"_posts","_blog","_featured","_data","_authors"]

compress_html:
  clippings: all


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar

sass:
    sass_dir: _sass

scholar:
  bibliography_template: bib
  sort_by: year
  order: descending
  bibtex_filters: 
    - superscript
    - latex

collections:
  authors:
    output: true
    permalink: author/:title/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: post




